config/routes.rb
Rails.application.routes.draw do
  # エンドユーザー用
  devise_for :end_users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :end_user do
    post "end_users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root :to => "homes#top"
    get "end_users" => redirect("end_users/sign_up")
    get "about" => "homes#about"
    get "search" => "homes#search"
    get "ranking" => "cats#ranking"
    get "end_users/withdraw_confirm" => "end_users#withdraw_confirm", as: "withdraw_confirm"
    patch "end_users/withdraw" => "end_users#withdraw"
    resources :end_users, only: [:show, :edit, :update] do
      get "bookmark_cats" => "end_users#bookmark_cats"
    end
    resources :cats, only: [:new, :create, :show, :edit, :update] do
      resource :bookmarks, only: [:create, :destroy]
    end
    resources :posts do
      resource :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
   get "/" => "homes#top"
   get "search" => "homes#search"
   resources :posts, only: [:index, :show, :destroy] do
     resources :comments, only: [:destroy]
   end
   resources :end_users, only: [:show, :edit, :update] do
     get "posts" => "end_users#posts_index", as: "posts_index"
   end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :end_user
  belongs_to :post

  validates :comment_content, presence: true, length: { maximum: 250 }
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/_comment_count.html.erb
<%= post.comments.count %>件のコメント

app/views/admin/comments/_index.html.erb
<% post.comments.each do |comment| %>
  <div class="media border mb-3">
    <div class="media-body ml-4 p-3">
      <p>
        <%= comment.created_at.strftime('%Y/%m/%d') %>
        <%= link_to admin_end_user_path(comment.end_user) do %>
          <%= comment.end_user.name %>
        <% end %>
      </p>
      <p class="text-break"><%= comment.comment_content %></p>
      <div class="d-flex justify-content-end">
        <%= link_to "削除する", admin_post_comment_path(post, comment), method: :delete, remote: true, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/comments/destroy.js.erb
$('.comment-index').html("<%= j(render "admin/comments/index", post: @comment.post) %>");
$('.comment-count').html("<%= j(render "public/comments/comment_count", post: @comment.post) %>");