config/routes.rb
Rails.application.routes.draw do
  # エンドユーザー用
  devise_for :end_users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :end_user do
    post "end_users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root :to => "homes#top"
    get "end_users" => redirect("end_users/sign_up")
    get "about" => "homes#about"
    get "search" => "homes#search"
    get "ranking" => "cats#ranking"
    get "end_users/withdraw_confirm" => "end_users#withdraw_confirm", as: "withdraw_confirm"
    patch "end_users/withdraw" => "end_users#withdraw"
    resources :end_users, only: [:show, :edit, :update] do
      get "bookmark_cats" => "end_users#bookmark_cats"
    end
    resources :cats, only: [:new, :create, :show, :edit, :update] do
      resource :bookmarks, only: [:create, :destroy]
    end
    resources :posts do
      resource :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
   get "/" => "homes#top"
   get "search" => "homes#search"
   resources :posts, only: [:index, :show, :destroy] do
     resources :comments, only: [:destroy]
   end
   resources :end_users, only: [:show, :edit, :update] do
     get "posts" => "end_users#posts_index", as: "posts_index"
   end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :end_user
  belongs_to :cat
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  scope :valid_posts, -> { joins(:end_user).where(end_user: { is_deleted: false }) }

  has_one_attached :image

  validates :title, presence: true, length: { maximum: 15 }
  validates :body, presence: true, length: { maximum: 200 }
  validates :cat_id, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image1.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  # いいねしているかチェックする
  def liked_by?(end_user)
    likes.exists?(end_user_id: end_user.id)
  end

  # 自分の投稿かチェックする
  def is_own_post?(current_end_user)
    end_user == current_end_user
  end

  # タグの保存
  def save_tags(savepost_tags)
    # 既にその投稿に基づいたタグがあればタグのnameをcurrent_tagsに代入
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 新しく保存されたタグとの差分をそれぞれ変数に代入する
    old_tags = current_tags - savepost_tags
    new_tags = savepost_tags - current_tags

    #古いタグの削除
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name: old_name)
    end

    #新しいタグの保存
    new_tags.each do |new_name|
      book_tag = Tag.find_or_create_by(name: new_name)
      self.tags << book_tag
    end
  end

  def self.search_for(search_word, method)
    if method == "perfect"
      Post.where(title: search_word)
    elsif method == "forward"
      Post.where("title LIKE ?", "#{search_word}%")
    elsif method == "backward"
      Post.where("title LIKE ?", "%#{search_word}")
    else
      Post.where("title LIKE ?", "%#{search_word}%")
    end
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @posts = Post.order("created_at DESC").page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    Post.find(params[:id]).destroy
    flash[:warning] = "投稿を削除しました。"
    redirect_to admin_posts_path
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_index.html.erb
<div class="row">
  <% posts.each do |post| %>
    <div class="card w-75 mx-auto mb-5 shadow-lg">
      <%= link_to admin_post_path(post) do %>
        <%= image_tag post.get_image(800,600), class: "card-img-top" %>
      <% end %>
      <div class="card-body">
        <div class="row align-items-center">
          <div class="col-4 text-center">
            <%= image_tag post.cat.get_cat_image(200,200), class: "cat-img cat-img-post" %>
            <p class="text-center mt-2"><%= post.cat.name %></p>
          </div>
          <div class="col-6 offset-1">
            <p class="card-title">
              <%= link_to admin_post_path(post) do %>
                <strong><%= post.title %></strong>
              <% end %>
            </p>
            <p>
              <%= render "admin/posts/tag_link", post: post %>
            </p>
            <p><%= post.comments.count %>コメント</p>
            <span><%= post.created_at.strftime('%Y/%m/%d') %></span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="row justify-content-center">
  <%= paginate posts, theme: 'bootstrap-5' %>
</div>

app/views/admin/posts/_tag_link.html.erb
<% post.tags.each do |tag| %>
  <li style="list-style: none;">
    <%= link_to "##{tag.name}", admin_search_path(search_word: tag.name, model: "tag", method: "perfect") %>
  </li>
<% end %>

app/views/admin/posts/index.html.erb
<div class="container">
  <h3 class="mt-5">投稿一覧</h3>
  <div class="row mt-3">
    <div class="col">
      <%= render "index", posts: @posts %>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <h3 class="my-5">投稿詳細</h3>
  <div class="row">
    <div class="card w-75 mx-auto">
      <%= image_tag @post.get_image(800,600), class: "card-img-top" %>
      <div class="card-body">
        <div class="row align-items-center">
          <div class="col-4 text-center">
              <%= image_tag @post.cat.get_cat_image(200,200), class: "cat-img cat-img-post" %><br>
              <p class="text-center mt-2"><%= @post.cat.name %></p>
          </div>
          <div class="col-8">
            <p>タイトル</p>
            <p class="card-title pl-3">
              <%= @post.title %>
            </p>
            <p>内容</p>
            <p class="card-text pl-3 text-break">
              <%= @post.body %>
            </p>
            <p>タグ</p>
            <div class="ml-3">
              <%= render "admin/posts/tag_link", post: @post %>
            </div>
            <p class="mt-3"><%= @post.likes.count %>いいね</p>
            <span><%= @post.created_at.strftime('%Y/%m/%d') %></span>
            <div class="row justify-content-end">
              <%= link_to "削除する", admin_post_path(@post), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-danger" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <h5 class="comment-count mt-5"><%= render "admin/comments/comment_count", post: @post %></h5>
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <div class="comment-index">
        <%= render "admin/comments/index", post: @post %>
      </div>
    </div>
  </div>
</div>