config/routes.rb
Rails.application.routes.draw do
  # エンドユーザー用
  devise_for :end_users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :end_user do
    post "end_users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root :to => "homes#top"
    get "end_users" => redirect("end_users/sign_up")
    get "about" => "homes#about"
    get "search" => "homes#search"
    get "ranking" => "cats#ranking"
    get "end_users/withdraw_confirm" => "end_users#withdraw_confirm", as: "withdraw_confirm"
    patch "end_users/withdraw" => "end_users#withdraw"
    resources :end_users, only: [:show, :edit, :update] do
      get "bookmark_cats" => "end_users#bookmark_cats"
    end
    resources :cats, only: [:new, :create, :show, :edit, :update] do
      resource :bookmarks, only: [:create, :destroy]
    end
    resources :posts do
      resource :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
   get "/" => "homes#top"
   get "search" => "homes#search"
   resources :posts, only: [:index, :show, :destroy] do
     resources :comments, only: [:destroy]
   end
   resources :end_users, only: [:show, :edit, :update] do
     get "posts" => "end_users#posts_index", as: "posts_index"
   end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cats, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_cats, through: :bookmarks, source: :cat

  validates :name, length: { in: 1..10 }, uniqueness: true
  validates :introduction, length: { maximum: 500 }

  # 猫をブックマークしているかチェックする
  def bookmarked?(cat)
    bookmark_cats.include?(cat)
  end

  def self.search_for(search_word, method)
    if method == "perfect"
      EndUser.where(name: search_word)
    elsif method == "forward"
      EndUser.where("name LIKE ?", "#{search_word}%")
    elsif method == "backward"
      EndUser.where("name LIKE ?", "%#{search_word}")
    else
      EndUser.where("name LIKE ?", "%#{search_word}%")
    end
  end

  def self.guest
    find_or_create_by!(name: 'guestuser', email: 'guest@example.com') do |end_user|
      end_user.password = SecureRandom.urlsafe_base64
    end
  end

end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :find_end_user, only: [:show, :edit, :update]

  def show
    @cats = @end_user.cats.page(params[:page]).per(3)
  end

  def edit
  end

  def update
    if @end_user.update(end_user_params)
      redirect_to admin_end_user_path(@end_user)
      flash[:notice] = "ステータスを変更しました。"
    else
      render :edit
    end
  end

  def posts_index
    @end_user = EndUser.find(params[:end_user_id])
    @posts = @end_user.posts.order("created_at DESC").page(params[:page])
  end


  private

  def end_user_params
    params.require(:end_user).permit(:name, :introduction, :email, :is_deleted)
  end

  def find_end_user
    @end_user = EndUser.find(params[:id])
  end
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/views/admin/end_users/_index.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th class="align-middle">ID</th>
      <th class="align-middle">ユーザー名</th>
      <th class="align-middle">投稿数</th>
      <th class="align-middle">ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% end_users.each do |end_user| %>
      <tr>
        <td class="align-middle"><%= end_user.id %></td>
        <td class="align-middle">
          <%= link_to admin_end_user_path(end_user) do %>
            <%= end_user.name %>
          <% end %>
        </td>
        <td class="align-middle"><%= end_user.posts.count %>投稿</td>
        <% if end_user.is_deleted == false %>
          <td class="text-success align-middle">有効</td>
        <% else %>
          <td class="text-secondary align-middle">退会</td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="d-flex justify-content-center">
  <%= paginate end_users, theme: 'bootstrap-5' %>
</div>

app/views/admin/end_users/edit.html.erb
<div class="container">
  <h3 class="mt-5">ユーザー編集</h3>
  <%= render "layouts/errors", obj: @end_user %>
  <div class="row justify-content-center">
    <div class="col-8 mt-5">
      <%= form_with model: @end_user, url: admin_end_user_path(@end_user) do |f| %>
        <div class="form-group">
          <%= f.label :name, "ユーザー名" %>
          <%= f.text_field :name, class: "form-control", placeholder: "10文字以内" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction, "自己紹介" %>
          <%= f.text_area :introduction, rows: '4', placeholder: "500文字以内", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :email, "メールアドレス" %>
          <%= f.text_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :is_deleted, "ステータス" %><br>
          <%= f.radio_button :is_deleted, false, class: "ml-3" %>
          <%= f.label :is_deleted, "有効" %>
          <%= f.radio_button :is_deleted, true, class: "ml-3" %>
          <%= f.label :is_deleted, "退会" %>
        </div>
        <div class="form-group">
          <%= f.submit "更新する", class: "btn btn-success float-right" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/end_users/post_index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h3><%= @end_user.name %>さんの投稿一覧</h3>
      <div class="row">
        <%= render "admin/posts/index", posts: @end_user.posts %>
      </div>
    </div>
  </div>
</div>

app/views/admin/end_users/posts_index.html.erb
<div class="container">
  <h3 class="mt-5"><%= @end_user.name %>さんの投稿一覧</h3>
  <div class="row mt-3">
    <div class="col">
      <%= render "admin/posts/index", posts: @posts %>
    </div>
  </div>
</div>

app/views/admin/end_users/show.html.erb
<div class="container">
  <h3 class="my-5">ユーザー詳細</h3>
  <div class="row">
    <div class="col-10">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <td class="col-3 align-middle">ユーザーID</td>
            <td class="align-middle"><%= @end_user.id %></td>
          </tr>
          <tr>
            <td class="align-middle">ユーザー名</td>
            <td class="align-middle"><%= @end_user.name %></td>
          </tr>
          <tr>
            <td class="align-middle">メールアドレス</td>
            <td class="align-middle"><%= @end_user.email %></td>
          </tr>
          <tr>
            <td class="align-middle">ステータス</td>
            <% if @end_user.is_deleted == false %>
              <td class="text-success">有効</td>
            <% else %>
              <td class="text-secondary">退会</td>
            <% end %>
          </tr>
          <tr>
            <td class="align-middle">自己紹介</td>
            <td class="text-break align-middle"><%= @end_user.introduction %></td>
          </tr>
        </tbody>
      </table>
      <div class="d-flex justify-content-end">
        <%= link_to "編集する", edit_admin_end_user_path(@end_user), class: "btn btn-success" %>
      </div>
      <div class="d-flex justify-content-end mt-3">
        <%= link_to "#{@end_user.name}さんの投稿一覧へ", admin_end_user_posts_index_path(@end_user) %>
      </div>
    </div>
  </div>
  <h5 class="my-5"><%= @end_user.name%>さんの猫ちゃん</h5>
  <div class="row">
    <div class="col-10 offset-1">
      <div class="row row-cols-1 row-cols-sm-3">
        <% @cats.each do |cat| %>
          <div class="col">
            <div class="card text-center">
              <div class="card-header">
                <%= image_tag cat.get_cat_image(200,200), class: "cat-img cat-img-user" %>
              </div>
              <div class="py-2">
                <%= cat.name %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="d-flex justify-content-center mt-3">
        <%= paginate @cats,  theme: 'bootstrap-5' %>
      </div>
    </div>
  </div>
</div>