config/routes.rb
Rails.application.routes.draw do
  # エンドユーザー用
  devise_for :end_users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :end_user do
    post "end_users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root :to => "homes#top"
    get "end_users" => redirect("end_users/sign_up")
    get "about" => "homes#about"
    get "search" => "homes#search"
    get "ranking" => "cats#ranking"
    get "end_users/withdraw_confirm" => "end_users#withdraw_confirm", as: "withdraw_confirm"
    patch "end_users/withdraw" => "end_users#withdraw"
    resources :end_users, only: [:show, :edit, :update] do
      get "bookmark_cats" => "end_users#bookmark_cats"
    end
    resources :cats, only: [:new, :create, :show, :edit, :update] do
      resource :bookmarks, only: [:create, :destroy]
    end
    resources :posts do
      resource :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
   get "/" => "homes#top"
   get "search" => "homes#search"
   resources :posts, only: [:index, :show, :destroy] do
     resources :comments, only: [:destroy]
   end
   resources :end_users, only: [:show, :edit, :update] do
     get "posts" => "end_users#posts_index", as: "posts_index"
   end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h5>
      <%= I18n.t("errors.messages.not_saved",
                 count: obj.errors.count,
                 obj: obj.class.model_name.human.downcase) #レシーバーのモデル名を取得
      %>
    </h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, class: "alert alert-#{bootstrap_alert(key)}") do %>
    <%= content_tag(:p, value) %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="pb-3">
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>猫と推しは世界を変える</p>
        <div class="admin-btn">
          <i class="fa-solid fa-cat admin-btn-cat bounce-cat"></i>
          <%= link_to "管理者ログイン", new_admin_session_path, class: 'admin-link' %>
        </div>
      </div>
    </div>
  </div>
  <%= javascript_include_tag "admin-btn" %>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <%= link_to (admin_signed_in? ? admin_path : root_path), class: "navbar-brand p-3" do %>
        <%= image_tag "oshineko-logo.png", size: "160x90" %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if end_user_signed_in? %>
            <li class="nav-item">
              <%= link_to "マイページ", end_user_path(current_end_user.id), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", posts_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ランキング", ranking_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "新規投稿", new_post_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "猫登録", new_cat_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_end_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "ユーザー一覧", admin_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", admin_posts_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "ログイン", new_end_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_end_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "About", about_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <div class="d-flex justify-content-first">
      <% if end_user_signed_in? %>
        <span class="bg-white p-2">ようこそ <%= current_end_user.name %> さん！</span>
      <% end %>
    </div>
    <div class="d-flex justify-content-end">
      <%= render "layouts/search_form" %>
    </div>
  </div>
</header>

app/views/layouts/_search_form.html.erb
<% if user_signed_in? %>
  <%= form_with url: (admin_signed_in? ? admin_search_path : search_path), method: :get do |f| %>
    <%= f.text_field :search_word, placeholder: "検索" %>
    <% if admin_signed_in? %>
      <%= f.select :model, options_for_select({"ユーザー" => "end_user", "投稿" => "post", "タグ" => "tag"}) %>
    <% else %>
      <%= f.select :model, options_for_select({"猫種" => "cat", "投稿" => "post", "タグ" => "tag"}) %>
    <% end %>
    <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
    <%= button_tag type: "submit", class: "btn btn-primary btn-sm mb-1" do %>
      <i class="fa-solid fa-magnifying-glass"></i>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OshiNeko</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/0e2769a502.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main class="mb-auto">
      <%= render "layouts/flash" %>
      <%= yield %>
      <span id="back">
        <%= link_to "#" do %>
          <i class="fa-solid fa-paw"></i>
        <% end %>
      </span>
    </main>
    <%= render "layouts/footer" %>
    <%= javascript_include_tag "upper-button" %>
  </body>
</html>